title: Riding Rails
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - CNAME
permalink: "/:year/:i_month/:i_day/:title/"
markdown: kramdown
category_dir: ""
category_title_prefix: ""
twitter:
  username: rails
gems:
  - jemoji
  - jekyll-redirect-from
  - jekyll-seo-tag
defaults:
  - scope:
      path: ""
    values:
      image: https://avatars.githubusercontent.com/u/4223
